using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Source_Script_Manager
{
    public static class Keys
    {
        //contains all keys in one array
        //also includes functions to return phrase and literal versions of a key, based on the index
        //still doesnt feel like the best best way to do it, but honestly it's efficient. i'm always going to have to
        //search through a lot of things to find the specific key i'm looking for.

        //makin these not public because i want to encourage any functions to use the specific functions for getting keys.
        //a little more organized that way, since these functions can be modified once to modify the behavior in all classes similarly
        static readonly string[] key_phrase = //e.g. COMMA, PERIOD, SLASH, SEMICOLON, etc.
        {
            "!",
            "capslock",
            "tab",
            "numlock",
            "scrollock",
            "shift",
            "backspace",
            "enter",
            "semicolon",
            "escape",
            "space",
            "alt",
            "lwin",
            "rwin",
            "apps",
            "uparrow",
            "downarrow",
            "leftarrow",
            "rightarrow",
            "ins",
            "del",
            "pgdn",
            "pgup",
            "home",
            "end",
            "pause",

            "kp_end",
            "kp_downarrow",
            "kp_pgdn",
            "kp_leftarrow",
            "kp_5",
            "kp_rightarrow",
            "kp_home",
            "kp_uparrow",
            "kp_pgup",
            "kp_enter",
            "kp_ins",
            "kp_del",
            "kp_slash",
            "kp_multiply",
            "kp_minus",
            "kp_plus",

            "mwheeldown",
            "mwheelup",
            "mouse1",
            "mouse2",
            "mouse3",
            "mouse4",
            "mouse5",

            "joy1",
            "joy2",
            "joy3",
            "joy4",
            "joy5",
            "joy6",
            "joy7",
            "joy8",
            "joy9",
            "joy10",
            "joy11",
            "joy12",
            "joy13",
            "joy14",
            "joy15",
            "joy16",
            "joy17",
            "joy18",
            "joy19",
            "joy20",
            "joy21",
            "joy22",
            "joy23",
            "joy24",
            "joy25",
            "joy26",
            "joy27",
            "joy28",
            "joy29",
            "joy30",
            "joy31",
            "joy32",

            "aux1",
            "aux2",
            "aux3",
            "aux4",
            "aux5",
            "aux6",
            "aux7",
            "aux8",
            "aux9",
            "aux10",
            "aux11",
            "aux12",
            "aux13",
            "aux14",
            "aux15",
            "aux16",
            "aux17",
            "aux18",
            "aux19",
            "aux20",
            "aux21",
            "aux22",
            "aux23",
            "aux24",
            "aux25",
            "aux26",
            "aux27",
            "aux28",
            "aux29",
            "aux30",
            "aux31",
            "aux32",

            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",

            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "0",

            "f1",
            "f2",
            "f3",
            "f4",
            "f5",
            "f6",
            "f7",
            "f8",
            "f9",
            "f10",
            "f11",
            "f12",

            "minus",
            "equals",
            "obracket",
            "cbracket",
            "bslash",
            "apostrophe",
            "comma",
            "period",
            "fslash"
        };
        static readonly string[] key_literal = // e.g. ,./;'[]-=
        {
            "!",
            "capslock",
            "tab",
            "numlock",
            "scrollock",
            "shift",
            "backspace",
            "enter",
            "semicolon",
            "escape",
            "space",
            "alt",
            "lwin",
            "rwin",
            "apps",
            "uparrow",
            "downarrow",
            "leftarrow",
            "rightarrow",
            "ins",
            "del",
            "pgdn",
            "pgup",
            "home",
            "end",
            "pause",

            "kp_end",
            "kp_downarrow",
            "kp_pgdn",
            "kp_leftarrow",
            "kp_5",
            "kp_rightarrow",
            "kp_home",
            "kp_uparrow",
            "kp_pgup",
            "kp_enter",
            "kp_ins",
            "kp_del",
            "kp_slash",
            "kp_multiply",
            "kp_minus",
            "kp_plus",

            "mwheeldown",
            "mwheelup",
            "mouse1",
            "mouse2",
            "mouse3",
            "mouse4",
            "mouse5",

            "joy1",
            "joy2",
            "joy3",
            "joy4",
            "joy5",
            "joy6",
            "joy7",
            "joy8",
            "joy9",
            "joy10",
            "joy11",
            "joy12",
            "joy13",
            "joy14",
            "joy15",
            "joy16",
            "joy17",
            "joy18",
            "joy19",
            "joy20",
            "joy21",
            "joy22",
            "joy23",
            "joy24",
            "joy25",
            "joy26",
            "joy27",
            "joy28",
            "joy29",
            "joy30",
            "joy31",
            "joy32",

            "aux1",
            "aux2",
            "aux3",
            "aux4",
            "aux5",
            "aux6",
            "aux7",
            "aux8",
            "aux9",
            "aux10",
            "aux11",
            "aux12",
            "aux13",
            "aux14",
            "aux15",
            "aux16",
            "aux17",
            "aux18",
            "aux19",
            "aux20",
            "aux21",
            "aux22",
            "aux23",
            "aux24",
            "aux25",
            "aux26",
            "aux27",
            "aux28",
            "aux29",
            "aux30",
            "aux31",
            "aux32",

            "a",
            "b",
            "c",
            "d",
            "e",
            "f",
            "g",
            "h",
            "i",
            "j",
            "k",
            "l",
            "m",
            "n",
            "o",
            "p",
            "q",
            "r",
            "s",
            "t",
            "u",
            "v",
            "w",
            "x",
            "y",
            "z",

            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "0",

            "f1",
            "f2",
            "f3",
            "f4",
            "f5",
            "f6",
            "f7",
            "f8",
            "f9",
            "f10",
            "f11",
            "f12",

            "-",
            "=",
            "[",
            "]",
            "\\",
            "\'",
            ",",
            ".",
            "/"
        };

        //the one issue i can think of right now is when i have to go from a key in the file to a key in code - what do?
        //i need a way to do a search of all the keys in this file.
        //i think i'll need to put everything into an array so i can search them, then i'll create an identical array where instead there are all the key names; ' turns into apostrophe, for example.
        public static int GetIndex(string key)
        {
            if (key_phrase.Contains(key.ToLower()))
            {
                return Array.IndexOf(key_phrase, key.ToLower());
            }
            if (key_literal.Contains(key.ToLower()))
            {
                return Array.IndexOf(key_literal, key.ToLower());
            }
            return 0; //error code ! - that's what i've decided upon.
            //i'll get around to replacing all these exclamation marks with actual throw, try, and catch statements later. right now i just wanna get everything down.
        }
        public static string GetPhrase(int index)
        {
            return key_phrase[index];
        }
        public static string GetLiteral(int index)
        {
            return key_literal[index];
        }
    }
}
